### ISSUE TITLE
URLs in tables are not parsed

### ISSUE THREAD

**Issue by lidavidm** [CornellCSWiki/CornellCSWiki#3]
See any class page. Kramdown parses other Markdown in tables just fine, but for some reason links are not linkified unless explicitly linked (which is annoying).

**Comment by pniedzielski** [comment]
It looks like the URLs are not linked at all (e.g, line 83 on [CS4120](https://github.com/CornellCSWiki/CornellCSWiki/blob/master/classes/CS4120.md)).  URLs in Markdown have to be [surrounded by angle brackets](https://kramdown.gettalong.org/syntax.html#automatic-links) to become links.

PR incoming, if you could test that it fixes the problem, that would be great.
