### ISSUE TITLE
Getting Involved in CS/Open Source section needs to be updated

### ISSUE THREAD

**Issue by clairew** [CornellCSWiki/CornellCSWiki#35]
Add pages on how to get involved with open source on campus

**Comment by lidavidm** [comment]
If you have any ideas, that would be awesome :)

**Comment by pniedzielski** [comment]
David Li <notifications@github.com> skribis:
> If you have any ideas, that would be awesome :) 

Should this be tagged as low-hanging fruit, as something a new
contributor could do?

**Comment by lidavidm** [comment]
@pniedzielski good idea 👍

**Comment by lidavidm** [comment]
ok, the alignment on that emoji bothers me more than it should 
![image](https://user-images.githubusercontent.com/327919/32685776-ef458c24-c665-11e7-97c1-28a0653b913d.png)

**Comment by pniedzielski** [comment]
David Li <notifications@github.com> skribis:
> ok, the alignment on that emoji bothers me more than it should 
> ![image](https://user-images.githubusercontent.com/327919/32685776-ef458c24-c665-11e7-97c1-28a0653b913d.png) 

🥃

**Comment by rishi1999** [comment]
Unfortunately, the open-source scene on campus doesn't seem to be as active as it used to be. I can't find any information on active, relevant clubs or teams at Cornell. Closing this issue for now.
