### ISSUE TITLE
Change contributors list to be GitHub usernames as opposed to real names

### ISSUE THREAD

**Issue by mrkev** [CornellCSWiki/CornellCSWiki#51]
Thoughts? It'd make it easier to cross-reference too

**Comment by rishi1999** [comment]
I think this would make sense -- or another option is:

First Last (username)

**Comment by mrkev** [comment]
^ also down for this

**Comment by rishi1999** [comment]
I suppose nobody else has any input, so I think we should go ahead with the <First Last (username)> system.

**Comment by mrkev** [comment]
+1, PRs welcome 👍

**Comment by rishi1999** [comment]
Added info about the decision to `contributing.md`. I suppose we can close this issue now.
