### ISSUE TITLE
Add CS 4786

### ISSUE THREAD

**Issue by TrevorEdwards** [CornellCSWiki/CornellCSWiki#6]

**Comment by mrkev** [comment]
PR? 😁

**Comment by TrevorEdwards** [comment]
Maybe once I finish taking the class ;(

**Comment by lidavidm** [comment]
We could try and import class descriptions and engineering course reviews, at least. In fact, I wonder if we could generate something from the classes.cornell.edu API. Might play around with it if I'm bored.

**Comment by TrevorEdwards** [comment]
It would definitely lower the barrier to contributing if we had basic info prefilled for everything
