### ISSUE TITLE
fix jekyll-wikilinks-plugin

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#66]
Look at `contributing.md` for a good example of the issue. The markdown syntax isn't working properly, and as a result, the page is very cluttered and difficult to read.

**Comment by mrkev** [comment]
Can you post a screenshot? It looks good to me— or at least not any different than it ever did.

**Comment by rishi1999** [comment]
Interesting.. I was looking at the page on GitHub, and it seems that GitHub's flavor of markdown isn't able to render it. However, it does show up properly on the official site, so I suppose all is well.
