### ISSUE TITLE
Give contributor access to rishi1999

### ISSUE THREAD

**Issue by mrkev** [CornellCSWiki/CornellCSWiki#68]
Hey @rishi1999, I notice you're quite active in the repo. Would you like to be added to the CornellCSWiki org to effectively gain full permissions around the wiki?

I graduated in 2017 so getting a new maintainer is probably a good idea. I'm unsure if Open Source Cornell still promotes this wiki. It'd be good to post about it again in groups and such, or to reach out to URMC, WICC, or ACSU to raise awareness about it as both a resource to learn about courses and contribute information.

I like the collaborative nature of having this information on Github, and back when I was still at Cornell it was a good resource for "Intro to git/Github/open source contributing" type workshops too. I know student groups are sometimes in the lookout for opportunities to host teaching events.

In any case, let me know.

**Comment by rishi1999** [comment]
Hey @mrkev, I was actually meaning to ask about this -- I would love to be a maintainer for the wiki! It's definitely still used by students, but it could use a bit of advertisement. I'll see if I can get more students contributing to it over the next few months.

**Comment by mrkev** [comment]
Sounds good, sent the invite to the `CornellCSWiki` org. I think you just need to accept it and we're good to go (:
