### ISSUE TITLE
Website not updating to match GitHub repo

### ISSUE THREAD

**Issue by TrueshotBarrage** [CornellCSWiki/CornellCSWiki#72]
I edited the repo recently, and I noticed that the changes weren't updating on the actual website. Then I noticed that the list of contributors, which was updated in January 2019, was also not up to date, which indicates that the website has been out of sync with the repo since at least then.

**Comment by rishi1999** [comment]
Good find!

@mrkev do you know how to access the GitLab Pages content? I'm not sure what's going wrong here.

**Comment by lidavidm** [comment]
It's now building. https://gitlab.com/CornellCSWiki/cornellcswiki.gitlab.io/pipelines/110925007

**Comment by lidavidm** [comment]
@rishi1999 if you're now maintaining this, let me know your GitLab username and I can grant you access.

**Comment by lidavidm** [comment]
Oh, it failed. This will be fun.

**Comment by lidavidm** [comment]
I will get open-source approval from my employer to fix this, or if anyone else wants to step up, I can review. I believe all that's needed is the following, but don't want to mess with master.

```diff
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index 0bbc33f..9973c4b 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,7 +2,7 @@ image: ruby:2.3
 
 pages:
   script:
-  - gem install jekyll
+  - gem install jekyll --version 3.8
   - jekyll build -d public
   artifacts:
     paths:
```

**Comment by rishi1999** [comment]
Hi @lidavidm , my GitLab username is rishi1999.

To be honest, I don't have much experience with GitLab, so I would rather not be the one making the change. In the future, I can make simple fixes if and when they are necessary (once I'm a bit more familiar with it).

**Comment by lidavidm** [comment]
@rishi1999 I just added you, sorry for the delay.
The yaml file is part of the repo, shouldn't be too GitLab specific. I still haven't gotten approval, hopefully I can look soon...

**Comment by rishi1999** [comment]
Alright, I'll make the change -- we'll see if it works.

**Comment by rishi1999** [comment]
Everything works now. Thanks for the help @lidavidm !

**Comment by lidavidm** [comment]
Awesome, thanks for taking a look!
