### ISSUE TITLE
Add a favicon to the wiki

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#74]
Adding a favicon to the wiki would definitely make it look more aesthetically appealing :)

**Comment by dragon-girl88** [comment]
Hello!
Saw this comment today and liked your suggestion! So I made this.
Size: 27x29
![CSGithubFavicon](https://user-images.githubusercontent.com/69407676/89723732-21ae9e80-d9c8-11ea-80fa-80ffd82a5733.png)

Lmk what you think! I might make a few other designs!

**Comment by TrueshotBarrage** [comment]
That looks dope

**Comment by rishi1999** [comment]
That looks awesome!

I'll try adding it to the website when I get a chance.

**Comment by rishi1999** [comment]
Done! Finally got it to work.

If you don't see it when you load the page, try force reloading (Shift+F5).

**Comment by rishi1999** [comment]
Oh, forgot to mention - if you want to be added to the contributors list, let me know! It can be anonymous (just your username) or real name - up to you. Feel free to edit the Markdown file and submit a pull request, or if you would rather I did it, that's fine as well.
