### ISSUE TITLE
Many CS classes need pages created for them

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#75]
About half the classes listed on the homepage do not yet have pages created for them. We need to get these pages made and older pages updated to continue to be a relevant source of information for CS students at Cornell.

**Comment by kungpaogao** [comment]
Should we wait for #81 to be closed until creating new pages?

I have info for CS 5306 and BTRY 3080.

**Comment by rishi1999** [comment]
Yeah, let's figure out #81 first. Suggestions welcome :)

**Comment by rishi1999** [comment]
On second thought -- it seems like #81 will take some time to figure out -- feel free to add the new pages!

**Comment by rishi1999** [comment]
Also, I have removed the majority of the dead links on the homepage, but there are now plenty of CS courses that are not listed on the site. If anyone has information on a class that is not listed, feel free to make a new page!

**Comment by rishi1999** [comment]
These additions are no longer a high priority (see #89).
