### ISSUE TITLE
Math classes

### ISSUE THREAD

**Issue by louisel** [CornellCSWiki/CornellCSWiki#8]
Might be able to help out here, so a quick question: is this more of the required classes such as MATH 1920/2210 kind of classes, classes that are of interest such as MATH 4710/4740, or both types?

**Comment by mrkev** [comment]
both types! Contributions on this area are very welcome

**Comment by louisel** [comment]
I submitted a PR for this. I only took MATH2230/2240, so information on the other lower level classes is appreciated.
