### ISSUE TITLE
Make contribution more accessible

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#80]
What's the best way to encourage participation in contributing to the wiki? Having to commit PRs, etc. seems to be a somewhat high barrier to entry. I think another big reason is the desire for anonymity. Perhaps we could set up some sort of anonymous form where people can add their feedback? Thoughts?

**Comment by kungpaogao** [comment]
We could try using a CMS (like [Netlify CMS](https://www.netlifycms.org/)), but this would mean that we would have to adjust our hosting.

Using a form would probably require a lot of manual work to keep the markdown files updated.

**Comment by rishi1999** [comment]
Hmm, do you have experience with this? How much work would go into setting it up? What are some of the pros/cons?

**Comment by kungpaogao** [comment]
I forgot to respond earlier, but I don't have any experience. Pros would be that it's more accessible since you can edit more easily than going through GitHub PRs. Cons would definitely be the setup and maintenance time.

**Comment by rishi1999** [comment]
Following the discussion in #89, most contributions will not need to be anonymous and will largely consist of bugfixes and maintenance. With that in mind, I think the current setup is plenty accessible.
