### ISSUE TITLE
Revamp class page format

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#81]
Some of the sections seem to be somewhat redundant (e.g., general advice / testimonials). Also, some of the information becomes outdated very quick (e.g., past offerings). Suggestions on how to improve the structure?

**Comment by dragon-girl88** [comment]
Can we have something that says "current professor" and have the past offerings below it? Cause the professor can really change how the course runs.

**Comment by rishi1999** [comment]
Good idea! You can edit the `class_template.md` file to make the change. Lmk if you need help with anything.

**Comment by rishi1999** [comment]
Another important piece of information that is often missing is the date/semester that the feedback was submitted. The quality of a course can change a *lot* from year to year, and I think it's important that the format we use accounts for that.

**Comment by rishi1999** [comment]
Made some changes, and I think it's ok for now. If we decide to start using a CMS, as suggested in #80, we can make more major changes.
