### ISSUE TITLE
Label core classes

### ISSUE THREAD

**Issue by dragon-girl88** [CornellCSWiki/CornellCSWiki#85]
This is probably a little minor, but I think labeling CS major core classes (111x, 211x, 3110, 3410/20, 4410, 4820) will make it easier for people to spot them if they want info about them

**Comment by rishi1999** [comment]
Feel free to modify it as you see fit!

**Comment by kungpaogao** [comment]
Should we define core the same way that the CS major requirements defines them? They count 111x and 211x as "introductory programming," but most people would just call them core classes.

https://www.cs.cornell.edu/undergrad/csmajor

**Comment by kungpaogao** [comment]
That aside, this is what I've come up with:

![image](https://user-images.githubusercontent.com/11168401/93164903-aa67db00-f6e8-11ea-8034-abfefdfcaa26.png)

**Comment by rishi1999** [comment]
I think it's fair to call the intro classes "core" classes. And that looks really good!
